### ISSUE TITLE
[Feature Request] Enable Send email as another workflow to nudge the users

### ISSUE THREAD

**Issue by contactvaibhavi** [dellsystem/github-streak-saver#4]
Thank you for this wonderful project!

I noticed the Twilio Free API has limits on <40 SMS in a mth or so. Thus, it's better to use an alternative workflow to send the reminders. 

Email notifs would suffice for a nudge to the user. @dellsystem What are your views? :) 

I'm willing to work on this.

**Comment by dellsystem** [comment]
look i'm sorry but i haven't updated this repo in 9 years. i really don't care. you can do whatever you want.

**Comment by contactvaibhavi** [comment]
> look i'm sorry but i haven't updated this repo in 9 years. i really don't care. you can do whatever you want.

Hey I understand 🙂
Will modify it as per need, thank u!
